### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by sysworx** [rootforbid/Emby.Plugins.Gotify#1]
Actual this plugin doesnt work, it gives a endless loading animation on the user select.

Browser Debug Console:

`VM1366:82 Uncaught (in promise) TypeError: $(...).html(...).selectmenu is not a function
    at <anonymous>:82:25
/Plugins/E29621A5-FA9E-4330-982E-EF6E54C0CAD2/Configuration?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome&X-Emby-Device-Id=7XXX5XXX48fd-XXXXXXXX&X-Emby-Client-Version=4.5.2.0&X-Emby-Token=XXXXXXXXXXXX81:1 Failed to load resource: the server responded with a status of 500 ()
index.html#!/configurationpage?name=Gotify%20Notifications:1 Uncaught (in promise) Response
`

**Comment by rootforbid** [comment]
> Actual this plugin doesnt work, it gives a endless loading animation on the user select.
> 
> Browser Debug Console:
> 
> `VM1366:82 Uncaught (in promise) TypeError: $(...).html(...).selectmenu is not a function at <anonymous>:82:25 /Plugins/E29621A5-FA9E-4330-982E-EF6E54C0CAD2/Configuration?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome&X-Emby-Device-Id=7XXX5XXX48fd-XXXXXXXX&X-Emby-Client-Version=4.5.2.0&X-Emby-Token=XXXXXXXXXXXX81:1 Failed to load resource: the server responded with a status of 500 () index.html#!/configurationpage?name=Gotify%20Notifications:1 Uncaught (in promise) Response `

A couple things I need you to troubleshoot:
- have you restarted Emby Server?
- this plugin is a carbon copy of the official Emby plugin "Pushover" that is available in the catalog. Can you install it and see if you have the same problem when trying the select a user? Make sure to restart Emby Server after intalling the plugin.
- What OS is used for your Emby Server? I see that you're using it in a VM. Check the file permissions on the "MediaBrowser.Plugins.GotifyNotifications.dll" file.
- Do you have other plugins installed?
- Does your user list load fine in Emby Server management page under Server > Users? Does an individual user load fine when you click on it?
- Are your users "local users" or "Emby Connect" users?
- Do you mod your Emby Server in any way?

I'm asking all these because I use this plugin daily with no problems and so are a handful of people.
I just tried it again on a fresh new install and it works fine.
From the log, it looks like the plugins receives an error because Emby errors out when trying to send back the user list.

**Comment by sysworx** [comment]
A couple things I need you to troubleshoot:

- have you restarted Emby Server?
Yes
- this plugin is a carbon copy of the official Emby plugin "Pushover" that is available in the catalog. Can you install it and see if you have the same problem when trying the select a user? Make sure to restart Emby Server after intalling the plugin.
Pushover runs fine
- What OS is used for your Emby Server? I see that you're using it in a VM. Check the file permissions on the "MediaBrowser.Plugins.GotifyNotifications.dll" file.
Windows with no VM, no permission needed
- Do you have other plugins installed?
yes
- Does your user list load fine in Emby Server management page under Server > Users? Does an individual user load fine when you click on it?
yes
- Are your users "local users" or "Emby Connect" users?
local users
- Do you mod your Emby Server in any way?
no

For me it seems to be a failure in the plugin:

> VM161:82 Uncaught (in promise) TypeError: $(...).html(...).selectmenu is not a function
>     at <anonymous>:82:25
> VM161:19 Uncaught (in promise) TypeError: $(...).checked is not a function
>     at <anonymous>:19:49

Emby is on 4.5.2.0

**Comment by rootforbid** [comment]
Sorry, thanksgiving over here.

What browser are you using to access your Emby admin panel?
Clear your browser's cache and restart your browser.

I sometimes get instances of uncaught promises (different one than yours) when trying to access the plugin's configuration page. The plugin page would not load at all.
Restarting my browser (Firefox) does the job. I don't have this issue on Chrome but then, my Firefox browser stays open 24/7 unlike Chrome.
I also noticed this bug seems to only apply to plugins not installed from the catalog (like this one).

If this does not solve your issue I don't know what else to do since I can't exactly reproduce your bug.

If you're really desperate to get this working nevertheless, maybe you can try this (no clue if it will work):

1. In your plugins folder where MediaBrowser.Plugins.GotifyNotifications.dll is located, create a folder (if it's not already there) named "configurations", then navigate to it.
2. Now that you're inside the "configurations" folder, create a XML file named "MediaBrowser.Plugins.GotifyNotifications.xml"
3. You will need 3 things: your Gotify url (**no trailing slash**), your Gotify token and the MediaBrowserUserId of the Emby user who will be notified (I'll explain how to get this right next).
4. How to get your user id: In Emby's admin panel, go to Advanced > Api Keys
5. Create a new Api Key by clicking the "+ New Api Key" button
6. Give whatever name you want
7. Copy your Api key and go to the url: `http://emby-ip-address:emby-port/emby/Users?api_key=YOUR-API-KEY`
For example: http://192.168.1.133:8096/emby/Users?api_key=a017b6401a3d44c08a6fa6120ebb5d55
You will get a wall of text, but basically it's a list of all your users with some of their Emby details.
9. Locate the line that contains `"Name": "YourUserName"`, replace YourUserName with your actual username.
In my case I'd need to find `"Name": "rootforbid"`
10. What should follow are: `"ServerId": "YourServerId", "Id": "YourUserId"`; "YourUserId" is what you need. Copy it somewhere.
11. Open "MediaBrowser.Plugins.GotifyNotifications.xml" and paste the following:
```
<?xml version="1.0"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Options>
    <GotifyOptions>
      <Enabled>true</Enabled>
      <Url>https://your-gotify-server-url.com</Url>
      <Token>yourGotifyToken</Token>
      <MediaBrowserUserId>yourUserIdYouJustCopied</MediaBrowserUserId>
    </GotifyOptions>
  </Options>
</PluginConfiguration>
```
If you need to notify more than 1 user, repeat from step 7 to get the user IDs of the extra users and add another GotifyOptions segment per user as follows:
```
<?xml version="1.0"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Options>
    <GotifyOptions>
      <Enabled>true</Enabled>
      <Url>https://your-gotify-server-url.com</Url>
      <Token>yourGotifyToken</Token>
      <MediaBrowserUserId>yourUserIdYouJustCopied</MediaBrowserUserId>
    </GotifyOptions>
    <GotifyOptions>
      <Enabled>true</Enabled>
      <Url>https://your-gotify-server-url.com</Url>
      <Token>yourGotifyToken</Token>
      <MediaBrowserUserId>userIDofUser2</MediaBrowserUserId>
    </GotifyOptions>
    <GotifyOptions>
      <Enabled>true</Enabled>
      <Url>https://your-gotify-server-url.com</Url>
      <Token>yourGotifyToken</Token>
      <MediaBrowserUserId>userIDofUser3</MediaBrowserUserId>
    </GotifyOptions>
    ...
  </Options>
</PluginConfiguration>
```
11. Close and save the file
12. Reboot Emby Server
13. To test it out, go to Emby's admin panel > Advanced > Notifications > User > "Video playback started"
14. Check the following: "Enable this notification", Monitor activity from "select all the users", Send the notification to "Custom", Select users: "select the users you entered user IDs for in the XML file", Use the following services: "select Gotify Notifications"
15. Hit "Save"
16. Start playing a video and hope you get a notification.

**Comment by sysworx** [comment]
No problem ;)
The browser doesnt matter, it happens on any browser of any OS.

As Luke mentioned, the plugin needs a update:
mentioned here: https://emby.media/community/index.php?/topic/91573-cant-change-notifications/&tab=comments#comment-952222

**Comment by rootforbid** [comment]
With the Gotify and Pushover plugins installed, create an API key (if you haven't already). I described how to do this in step 4.
And then, can you paste the results you get when browsing to: `http://EMBY_SERVER_URL/emby/Plugins?api_key=YOUR_API_KEY`
There's no personal identifying information in the results so no worries.

I'm sorry to ask you all this but because I can't reproduce your bug, I need to rule out any kind of differentiation.

**Comment by sysworx** [comment]
Ok i did this 👍 

`[{"Name":"Bluray Folder Support","Version":"1.0.0.0","Description":"Adds Bluray folder support to Emby Server","Id":"ed4b9001-e4a1-4760-9592-d127188ef178","ImageTag":"1"},{"Name":"Dlna","Version":"1.0.39.0","Description":"Dlna","Id":"8c6ddb20-18b1-4131-9285-796179a71c0f","ImageTag":"1"},{"Name":"Dvd Folder Support","Version":"1.0.0.0","Description":"Adds Dvd folder support to Emby Server","Id":"4c7a45d6-f859-4242-9cda-aea1977969de","ImageTag":"1"},{"Name":"Email Notifications","Version":"3.1.6.0","ConfigurationFileName":"MediaBrowser.Plugins.SmtpNotifications.xml","Description":"Sends notifications via email.","Id":"b9f0c474-e9a8-4292-ae41-eb3c1542f4cd","ImageTag":"1"},{"Name":"Fanart.tv","Version":"1.0.10.0","Description":"Fanart.tv","Id":"8d7d93b2-01dc-48dc-8c5d-4e7abbd9f9eb","ImageTag":"1"},{"Name":"Gotify Notifications","Version":"1.0.0.0","ConfigurationFileName":"MediaBrowser.Plugins.GotifyNotifications.xml","Description":"Sends notifications via Gotify Service.","Id":"4002dda8-022c-47a9-bdb7-2847636bb73a","ImageTag":"1"},{"Name":"IMVDb","Version":"1.0.8.0","Description":"IMVDb metadata for musiv videos","Id":"0277e613-3ec0-4360-a3de-f8af0aabb5e9","ImageTag":"1"},{"Name":"InfuseSync","Version":"1.2.4.0","ConfigurationFileName":"InfuseSync.xml","Description":"Plugin for fast synchronization with Infuse.","Id":"022a3003-993f-45f1-8565-87d12af2e12a","ImageTag":"1"},{"Name":"MovieDb","Version":"1.3.8.0","Description":"MovieDb metadata for movies","Id":"3a63a9f3-810e-44f6-910a-14d6ad1255ec","ImageTag":"1"},{"Name":"Nfo Metadata","Version":"1.0.34.0","Description":"Nfo metadata support","Id":"e610ba80-9750-47bc-979d-3f0fc86e0081","ImageTag":"1"},{"Name":"OMDb","Version":"1.0.11.0","Description":"OMDb","Id":"c25b3c85-1880-4827-9c72-0fa74314f428","ImageTag":"1"},{"Name":"Playback Reporting","Version":"1.7.0.3","ConfigurationFileName":"playback_reporting.xml","Description":"Show reports for playback activity","Id":"9e6eb40f-9a1a-4ca1-a299-62b4d252453e","ImageTag":"1"},{"Name":"Port Mapper","Version":"1.0.4.0","Description":"Port Mapper","Id":"96fa50a4-69ce-42ac-b6a3-ef6b3388ccb7","ImageTag":"1"},{"Name":"Pushover Notifications","Version":"3.1.3.0","ConfigurationFileName":"MediaBrowser.Plugins.PushOverNotifications.xml","Description":"Sends notifications via Pushover Service.","Id":"6c3b6965-c257-47c2-aa02-64457ae21d91","ImageTag":"1"},{"Name":"Reports","Version":"1.0.44.0","ConfigurationFileName":"EmbyReports.xml","Description":"Generate Reports","Id":"2fe79c34-c9dc-4d94-9df2-2f3f36764414","ImageTag":"1"},{"Name":"Server Configuration Backup","Version":"1.4.5.0","ConfigurationFileName":"MBBackup.xml","Description":"Emby Backup for your collection.","Id":"e711475e-efad-431b-8527-033ba9873a34","ImageTag":"1"},{"Name":"Studio Images","Version":"1.0.3.0","Description":"Emby Studio Images","Id":"c68856b8-6031-480d-b08e-43b9114addb2","ImageTag":"1"},{"Name":"TheAudioDb","Version":"1.0.11.0","Description":"TheAudioDb","Id":"18cffd2c-74f5-4ede-8dad-be339443afe4","ImageTag":"1"},{"Name":"TheTVDB","Version":"1.0.35.0","Description":"Tvdb metadata for Tv shows","Id":"7fb7ff5e-5407-4f74-8990-b7aa643085d2","ImageTag":"1"}]`

**Comment by rootforbid** [comment]
Thanks for the json. Looks like the plugin is reporting the correct id. I thought that could be the culprit.
I'm gonna ask Luke if he can look into this since I'm using the code of his Pushover plugin. The guy who's doing the Telegram plugin uses that same code too and you're having trouble with it so...
My suspicion is it's probably Emby itself that has a bug. Maybe it somehow treats catalogued plugins in a different way than external plugins.
But then, you're the only one so far that has had this bug. Nobody reported such a bug for the Telegram plugin either.
So it could be on your end, but so far I didn't see anything wrong on your setup.
Maybe the plugin is conflicting with another but I highly doubt it.

Normally for debugging, I'd ask you to install the plugin on a fresh new install of Emby. But I understand that it's a big ask since setting up all your libraries, users, etc... again can be a pain.
If Luke can help, expect him to ask you that though.

**Comment by sysworx** [comment]
i searched the emby forum for that error, Luke mentioned some solution in a other post:

`the plugin will need an update to remove usage of jquery selectmenu and checked() functions. Just convert that to plain javascript and it will work with bold old and new servers.`

It seems the plugin uses a old method from jquery, maybe that will help you ;)

**Comment by rootforbid** [comment]
> i searched the emby forum for that error, Luke mentioned some solution in a other post:
> 
> `the plugin will need an update to remove usage of jquery selectmenu and checked() functions. Just convert that to plain javascript and it will work with bold old and new servers.`
> 
> It seems the plugin uses a old method from jquery, maybe that will help you ;)

Well it actually helped and didn't help.
It helped in the sense that I identified that's it's not caused by this plugin.
And it didn't help because the suggestion doesn't apply to my plugin.

Let me explain.
I just noticed it talking with Luke, but from the log in your first post here, the GET request is from another plugin.
The plugin id doesn't match my plugin id at all.
And to confirm it, you're getting an error response from a function (selectmenu) that doesn't even exist in my plugin.
And the other function (checked) is actually already a plain javascript function in my code. It doesn't use jQuery.

So there must be another plugin conflicting; a plugin that uses the "selectmenu" function that is causing the problem.
The only way to know is for you to run another instance of Emby (so you can preserve your current one) as a clean install and install the Gotify plugin only and make sure the new instance is not using the same plugin directory as your current instance.

On my end, on my current Emby server and a clean install, the Gotify plugin works no problem on both and so does the Telegram plugin.

Unless you have a way for me to reproduce this, I can't be anymore of help I'm afraid.

I will label this as "can not reproduce".

**Comment by sysworx** [comment]
Hey 🙂,

i did some further research and deinstalled the plugin InfuseSync, now its working 👌
